name: cc-platform
services:
- name: web
  source_dir: /
  github:
    repo: EB-coder/CC_Platform
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: JWT_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: FRONTEND_URL
    value: ${_self.URL}
  http_port: 8080
  routes:
  - path: /
databases:
- name: db
  engine: PG
  version: "14"
  size: basic-xs
